apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-application
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: git@github.com:ttsooi/argocd-test.git
    targetRevision: HEAD
    path: sc4s/
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp