---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-data-20
  namespace: splunk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi